(load "/home/TDDA69/Lab/r6rs/constraints.ss")
(define C (make-connector))
(define F (make-connector))
(celsius-fahrenheit-converter C F)
(probe "Celsius" C)
(probe "Fahrenheit" F)
(set-value! C 25 'user)
(print "foo")
(define A (make-connector))
(define B (make-connector))
(define K (make-connector))
(print "bar")
(define (medel a b c)
  (let ((k (make-connector))
        (r (make-connector)))
    (adder a b r)
    (constant 0.5 k)
    (multiplier r k c)
    'ok))
(print "okok")
(medel A B K)
(print "aj")
(probe "A" A)
(probe "B" B)
(probe "K" K)

(set-value! A 10 'user)
(set-value! B 20 'user)